services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: qivo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: qivo_admin
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: qivo_global
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: