# HTTP → HTTPS
server {
    listen 80;
    server_name app.qivo.com www.app.qivo.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl;
    server_name app.qivo.com www.app.qivo.com;

    ssl_certificate /etc/letsencrypt/live/certs.afafslimi.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/certs.afafslimi.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}


